from scrape_id import *
from players_id import *

if __name__ == "__main__":
   #  test = [
   #      "Mahendra Singh Dhoni",
   #      "Devon Conway",
   #      "Ruturaj Gaikwad",
   #      "Ambati Rayudu",
   #      "Moeen Ali",
   #      "Mitchell Santner",
   #      "Ravindra Jadeja",
   #      "Deepak Chahar",
   #      "KL Rahul (capt)",
   #      "Quinton de Kock",
   #      "Marcus Stoinis",
   #      "Deepak Hooda",
   #      "Kyle Mayers",
   #      "Krunal Pandya",
   #      "Avesh Khan",
   #      "Ravi Bishnoi",
   #      "Rishabh Pant",
   #      "David Warner",
   #      "Prithvi Shaw",
   #      "Axar Patel",
   #      "Anrich Nortje",
   #      "Lungi Ngidi",
   #      "Mustafizur Rahman",
   #      "Kuldeep Yadav",
   #      "Sanju Samson",
   #      "Yashasvi Jaiswal",
   #      "Shimron Hetmyer",
   #      "Devdutt Padikkal",
   #      "Jos Buttler",
   #      "Riyan Parag",
   #      "Prasidh Krishna",
   #      "Trent Boult",
   #  ]
    test = [
        265,
        9838,
        11813,
        6311,
        6692,
        10100,
        587,
        7836,
        8261,
        8520,
        8989,
        9427,
        8440,
        11311,
        9781,
        14659,
        10744,
        1739,
        12094,
        8808,
        11427,
        9603,
        9863,
        8292,
        8271,
        13940,
        9789,
        13088,
        2258,
        12305,
        10551,
        8117,
    ]
    # scrap_Data(test)
    print(scrape_id(test))


    pass
